Criação do layout inicial e página dos clientes
LuisRotoly/CRPreparacoesFrontEnd pull request #1
Opened 2023-09-05 20:11 UTC by LuisRotoly

![image](https://github.com/LuisRotoly/CRPreparacoesFrontEnd/assets/109184689/693241b4-1b12-4fb0-bafb-997e9425f9d4)

![image](https://github.com/LuisRotoly/CRPreparacoesFrontEnd/assets/109184689/bb884730-887c-450d-8c17-43b17aa37353)

![image](https://github.com/LuisRotoly/CRPreparacoesFrontEnd/assets/109184689/fe7ac9fb-738e-41c5-935a-ded51aa6ab68)
Criar cliente usa o mesmo formulário
Não se importe muito com as outras páginas criadas

2023-09-06 01:49 UTC, gudominguete requested changes

2023-09-06 01:49 UTC, gudominguete commented on src/components/bar/TopBar.js
> +      </div>
tem um div a mais aqui, acho q pode remover eles

2023-09-06 01:49 UTC, gudominguete commented on src/components/bar/TopBarItem.js
> +  function getButtonClassname(pageUrl, url) {
Acho que colocar o nome da function como isButtonActive seria melhor aqui

2023-09-06 01:49 UTC, gudominguete commented on src/pages/DefaultLayout.js
> +function DefaultLayout() {
O que seria esse default Layout?

2023-09-06 14:19 UTC, LuisRotoly commented on src/pages/DefaultLayout.js
> +function DefaultLayout() {
É a tela "principal", ele tem todos os componentes padrões primeiro tipo o topbar, sidebar e tals e depois vc tem o outlet que são os conteúdos das páginas

2023-09-08 19:00 UTC, gudominguete approved these changes

2023-09-11 20:00 UTC, merged