Criando páginas das peças, motos e fornecedores
LuisRotoly/CRPreparacoesFrontEnd pull request #2
Opened 2023-09-12 19:09 UTC by LuisRotoly

Mesmas interfaces, só com dados diferentes

2023-09-13 00:31 UTC, gudominguete requested changes

2023-09-13 00:31 UTC, gudominguete commented on src/pages/bike/CreateBikePage.js
> +    for (let i = 0; i < brandList.length; i++) {
Usa o foreach aqui

2023-09-13 00:31 UTC, gudominguete commented on src/pages/bike/CreateBikePage.js
> +    //.catch((e) => setErrorMessage(e.response.data.message));
é pra deixar comentado?

2023-09-13 00:31 UTC, gudominguete commented on src/pages/bike/EditBikePage.js
> +    for (let i = 0; i < brandList.length; i++) {
Usar foreach

2023-09-13 10:49 UTC, LuisRotoly commented on src/pages/bike/CreateBikePage.js
> +    //.catch((e) => setErrorMessage(e.response.data.message));
é sim. Pra depois eu lembrar e criar os toasts

2023-09-14 03:09 UTC, gudominguete approved these changes

2023-09-14 11:29 UTC, merged