Transformando pré-orçamento em orçamento definitivo
LuisRotoly/CRPreparacoesFrontEnd pull request #22
Opened 2023-11-14 16:13 UTC by LuisRotoly

2023-11-14 23:34 UTC, gudominguete requested changes

2023-11-14 23:34 UTC, gudominguete commented on src/pages/budget/components/budget.css
> +  margin-bottom: -40px;
Pq da margin negativa? Geralmente nao faz isso pq eh um espaçamento da borda do elemento para o proximo. Então não faz muito sentido usar margin negativa

2023-11-14 23:34 UTC, gudominguete commented on src/pages/budget/sketch/TransformBudgetPage.js
> +                option.name + ", " + option.cpfcnpj + ", " + option.nickname
Criar uma função para retornar a label

2023-11-16 14:06 UTC, LuisRotoly commented on src/pages/budget/components/budget.css
> +  margin-bottom: -40px;
Preciso de ajuda, depois se vc puder eu agradeço

2023-11-17 11:44 UTC, merged